# Generated by Django 4.2.4 on 2024-01-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('No Category', 'No Category'), ('Accessories', 'Accessories'), ('Automobiles', 'Automobiles'), ('Clothing', 'Clothing'), ('Cosmetics', 'Cosmetics'), ('Devices', 'Devices'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Stationery', 'Stationery'), ('Utensils', 'Utensils')], default='No Category', max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField()),
                ('user', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('bid_user', models.CharField(max_length=50)),
                ('listing', models.CharField(max_length=50)),
                ('listing_catg', models.CharField(max_length=50)),
                ('listing_price', models.CharField(max_length=50)),
                ('listing_user', models.CharField(max_length=50)),
                ('time_posted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('comment_user', models.CharField(max_length=50)),
                ('listing', models.CharField(max_length=50)),
                ('listing_user', models.CharField(max_length=50)),
                ('time_posted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=50)),
                ('listing_category', models.CharField(max_length=50)),
                ('listing_description', models.TextField()),
                ('listing_price', models.CharField(max_length=50)),
                ('listing_user', models.CharField(max_length=50)),
                ('win_user', models.CharField(max_length=50)),
                ('win_amount', models.CharField(max_length=50)),
                ('time_closed', models.DateTimeField(null=True)),
            ],
        ),
    ]
